# Generated by Django 4.1.3 on 2022-12-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamPlatform',
            new_name='GamePlatform',
        ),
    ]
